### ISSUE TITLE
Simplified jupyter notebook examples

### ISSUE THREAD

**Issue by inureyes** [ragulpr/wtte-rnn#20]
* Currently, example jupyter notebook contains lots of information.
 * It leads users to be confused, also, the it affects to the total package size.

## Suggestion
 * [x] Make "Hello world" example notebook with tiny dataset (or generated dataset from embedded code)
 * [x] Create new repo for examples (need to discuss more. The best way is keeping one huge repo. without diverging it. However, we need to decrease the total package size)
 * [x] Gather good WTTE-RNN integrations / examples already on the web. It can be a new issue about manipulating `README.md` and GitHub Wiki.

**Comment by ragulpr** [comment]
Check out [examples repository](https://github.com/ragulpr/wtte-rnn-examples) created to save space and encourage viz. Pull request if you have examples that you want to add!
