### ISSUE TITLE
Should be >= K.epsilon()

### ISSUE THREAD

**Issue by gm-spacagna** [ragulpr/wtte-rnn#38]
At this line https://github.com/ragulpr/wtte-rnn/blob/aab74604496a58f295f7a82da5c35f5f64ca996d/python/wtte/wtte.py#L77 I see you are checking if K.epsilon() is <= 1e-7 and recommending to use a smaller value but then if you set it to 1e-08 it will still give the warning. You should change the operator to >=.

**Comment by ragulpr** [comment]
Nice thank you
