### ISSUE TITLE
ipython example breaks at Tensorflow 1.0.1

### ISSUE THREAD

**Issue by shane-huang** [ragulpr/wtte-rnn#5]
I'm running tensorflow 1.0.1 and tried the ipython notebook in the example folder. But it break at several points. It seems code is broken because of incompatibility of tensorflow versions. Which version of tensorflow have you used to developed your code? And is it possible to migrate this to Tensorflow 1.0? 

Thanks for the great work by the way. It's useful.

**Comment by ragulpr** [comment]
Hi there and thanks for pointing this out. I think the whole RNN-api has been restructured for the better and the TF-community has developed more good habits w.r.t how tf-code is written, something the ipynb at current doesn't reflect so the best is to just delete it.

Check out the branch [wtte-rnn-0.0.2](https://github.com/ragulpr/wtte-rnn/tree/wtte-rnn-0.0.2 )
and in particular the new [examples](https://github.com/ragulpr/wtte-rnn/tree/wtte-rnn-0.0.2/python/examples ). 

The data-pipeline is something of a WIP but I think the discretely padded pipe is working quite good, I just haven't gotten varying-length sequences down yet without using batch_size=1.

I'm going to be mainly focusing on getting a pipeline with continuous data similar to the Phased LSTM going but there's some math around it. Blog post coming up.

Would dearly welcome PRs and comments and don't be shy to (especially) comment on style and structure of the repo.

**Comment by ragulpr** [comment]
Passes with tensorflow 1.0.1

[ wtte-rnn/python/wtte/objectives/tensorflow.py ](https://github.com/ragulpr/wtte-rnn/python/wtte/objectives/tensorflow.py)

[ wtte-rnn/python/tests/test_tensorflow.py  ](https://github.com/ragulpr/wtte-rnn/blob/master/python/tests/test_tensorflow.py)
