### ISSUE TITLE
Porting WTTE-RNN to PyTorch

### ISSUE THREAD

**Issue by BraINstinct0** [ragulpr/wtte-rnn#71]
(both for personal use and practicing using PyTorch,) I'm planning to port WTTE-RNN to PyTorch.
What are the things (if any) that could be sort of a guide to port this?
also, (If I need it) is porting this permitted?
Sorry for mediocre English usage

**Comment by AlephNotation** [comment]
https://github.com/profil/tte.pytorch

**Comment by BraINstinct0** [comment]
> https://github.com/profil/tte.pytorch
Dunno why I missed it, thanks for letting me know
